name: 'App'

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Runner
        uses: ./
        id: runner
        with:
          github_labels: watch-domain
          github_token: ${{ secrets.GITHUB_TOKEN }}
